name: Build iOS IPA

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest

    env:
      GODOT_VERSION: 3.5.2

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python (for Godot headless export)
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Godot
        run: |
          wget https://downloads.tuxfamily.org/godotengine/${{ env.GODOT_VERSION }}/Godot_v${{ env.GODOT_VERSION }}-stable_osx.universal.zip -O godot.zip
          unzip godot.zip
          mv Godot.app /Applications/Godot.app

      - name: Install Godot Headless
        run: |
          wget https://downloads.tuxfamily.org/godotengine/${{ env.GODOT_VERSION }}/Godot_v${{ env.GODOT_VERSION }}-stable_osx_headless.64.zip -O godot-headless.zip
          unzip godot-headless.zip
          chmod +x Godot_v${{ env.GODOT_VERSION }}-stable_osx_headless.64
          mv Godot_v${{ env.GODOT_VERSION }}-stable_osx_headless.64 godot-headless

      - name: Add export templates
        run: |
          wget https://downloads.tuxfamily.org/godotengine/${{ env.GODOT_VERSION }}/Godot_v${{ env.GODOT_VERSION }}-stable_export_templates.tpz -O templates.tpz
          mkdir -p ~/.godot/templates/${{ env.GODOT_VERSION }}.stable
          tar -xvf templates.tpz -C ~/.godot/templates/${{ env.GODOT_VERSION }}.stable

      - name: Export iOS Project
        run: |
          mkdir -p build/ios
          ./godot-headless --export "iOS" build/ios/project.xcodeproj

      - name: Set up code signing files
        run: |
          mkdir -p ~/certs
          echo "$CERTIFICATE_BASE64" | base64 --decode > ~/certs/dist.p12
          echo "$PROVISIONING_PROFILE_BASE64" | base64 --decode > ~/certs/profile.mobileprovision

      - name: Install certificates
        env:
          CERT_PASSWORD: ${{ secrets.CERT_PASSWORD }}
        run: |
          security create-keychain -p "" build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p "" build.keychain
          security import ~/certs/dist.p12 -k build.keychain -P "$CERT_PASSWORD" -T /usr/bin/codesign
          security set-key-partition-list -S apple-tool:,apple: -s -k "" build.keychain

      - name: Copy provisioning profile
        run: |
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp ~/certs/profile.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/

      - name: Build IPA with Xcode
        run: |
          cd build/ios
          xcodebuild -project project.xcodeproj \
            -scheme "Godot iOS" \
            -configuration Release \
            -sdk iphoneos \
            -archivePath build/App.xcarchive \
            archive

          xcodebuild -exportArchive \
            -archivePath build/App.xcarchive \
            -exportPath build/exported \
            -exportOptionsPlist ../../exportOptions.plist

      - name: Upload IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-ipa
          path: build/ios/build/exported/*.ipa
